name: CI  # This is the name of the workflow that will be displayed in GitHub Actions UI and CI is a variable name

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  # This workflow will run on push and pull request events to the main branch

jobs:
  linting:  #linting is a variable name
    runs-on: ${{matrix.os}}  # This specifies the operating system on which the job will run, using a matrix strategy to allow for multiple OS types
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # This specifies the operating system on which the job will run
        python-version: ['3.9', '3.10']  # This specifies the Python version to use in the job

    steps:
      - name: code checkout
        uses: actions/checkout@v3 # This step checks out the code from the repository to the runner

      - name: setup python
        uses: actions/setup-python@v2  # This step sets up the Python environment on the runner
        with:
          python-version: ${{matrix.python-version}}  # Specify the Python version to use

      - name: install flake8
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          pip install flake8  # Install flake8 for linting Python code

      - name: run flake8
        run: |
          flake8 app.py  # Run flake8 on the current directory to check for linting issues
          echo "Linting completed successfully!"  # Print a success message if linting passes
        # continue-on-error: true  # Continue the workflow even if flake8 finds issues